source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SpriteKitUniversalMenus_Example' do
  pod "SpriteKitUniversalMenus", :path => "../"
end

target 'SpriteKitUniversalMenus_Tests' do
  pod "SpriteKitUniversalMenus", :path => "../"

  pod 'FBSnapshotTestCase'
end
