source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SpriteKitUniversalMenus-iOS' do
  pod "SpriteKitUniversalMenus", :path => "../"
end

target 'SpriteKitUniversalMenus-Mac' do
    pod "SpriteKitUniversalMenus", :path => "../"
end

target 'SpriteKitUniversalMenus-tvOS' do
    pod "SpriteKitUniversalMenus", :path => "../"
end

target 'SpriteKitUniversalMenus_Tests-iOS' do
  pod "SpriteKitUniversalMenus", :path => "../"

  pod 'FBSnapshotTestCase'
end

target 'SpriteKiUniversalMenus-MacUITests' do
    pod "SpriteKitUniversalMenus", :path => "../"
end

target 'SpriteKitUniversalMenus-tvOSUITests' do
    pod "SpriteKitUniversalMenus", :path => "../"
end